apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:y5GoDsJ3GlbuLZrRnXWQmFGtem38i7pNG114+OlOTveVPrxD4nhg70BZODQzrbdL0c/orupNwuwrmBqCdQ0LDlylMdDSkWIa,iv:g4s27NkzvGYI8NaY3fxUktiTUGQ8ctdHG8guiZcGhFU=,tag:W3nwvGJpKbbiHKtFhYzS/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVTA3TjUweWd1R09HS1Jm
            YU5leVU5RmNXd2hEN1FYa2p0RjBYekFuVkFJCkhOQ0ZtaGt1bkp1cGZrb3NLQ0w1
            TDJpNTdjVW5EMTFSK3JCdDNPUFdrSncKLS0tIGUxNktlcUdoUXFiVmRwSmphVy8y
            YTg1L2xyNC9JR1UwcEpMbWtaWlBaSWcKf1YpdGocZC09H2iFtV614wmU+HMpAPX+
            qRr75RVM2EJlY2ayFvJ5eIHYw7mA2EVhwvrpT6x9pArv4Kl1kswj7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T21:01:28Z"
    mac: ENC[AES256_GCM,data:akthThiA/OXj7OKHkyGE5bIDSgz7yirGDQXhZoeUAnr/Ufh85qL2z1ZHFf05dbLOSS4H+bdV+XVGSRHA8P/axtLyiTHVPog12hb77h7x01QpSMfHKf9J14+8xDPbr+yMljMy6GFVHrEmLrQuDrJ/Kbo52+i7a2HkC+DDdnKIlJM=,iv:vOE9K41vLXsnclFURH+VA7d7Whv3SKjQRFUTfXBRysY=,tag:8nYrqxHbWGgQe58gDlpkaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
