apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- limitrange.yaml
- cluster.yaml
- master.secrets.yaml
- deployment.yaml
- services.yaml
- oauth2-proxy.secrets.yaml
- oauth2-proxy.yaml
- httproute.yaml
- networkpolicy.yaml
- restore-test.yaml
