apiVersion: v1
kind: Service
metadata:
  name: agent-vault-api
  namespace: agent-vault
spec:
  type: ClusterIP
  selector:
    app: agent-vault
  ports:
  - name: api
    port: 14321
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: agent-vault-proxy
  namespace: agent-vault
spec:
  type: ClusterIP
  selector:
    app: agent-vault
  ports:
  - name: proxy
    port: 14322
    targetPort: proxy
