apiVersion: v1
kind: Secret
metadata:
    name: agora-web-database-url
    namespace: agora
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:yO+M92f8WSYpiX9ocF2hUmG7e17LX3tme6pkw/gDVUGDVaedVx8KTXlYxDsse7AMjTpl3nF4S3ILcwqiB9ecAHOhfCA179eQcqGwaBOjGJxteS0oNCXme4xZgOIgtRLzwNZ96m1laRWI8INoERz4y5NC3/q/jAmDIhlBCXb9cA==,iv:h0zRsI2HVNtkk27Wo+vJ7iH9Qzyky2C3JWS6DoiSf/M=,tag:zsXmtXPR9H3hgyZs7afHzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWEN2QjlRWGNKN3pFaFdq
            OVV2THZmYmpXeGg4dWxXY1dwN3hHZ2xDZHpJCmZlMkU5dkN3b1VHZVRMVDA2YTFl
            S2VZYm9JRlZQN0ZOL2RPTVE4MklHYUEKLS0tIFpuOFJvTjdNQ0JlMmNCM1hmZEZ1
            cXJSVk51Y3BUVjRPRlZMbVNxRGExWGMKdgUNjYxebN3/YI6lFje35Zi801hbwUdT
            89sz+k7XRwEP7s8e4Eie3mNY3+ghJJqL9ooqS6T6oX207YL6dR+/LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T20:13:22Z"
    mac: ENC[AES256_GCM,data:e05T1BwnhXuY3FH5D6wGB1tX3YFxDeUBzz9MfyAAXU0xvtjzj7/4PvSgYKtLiK4PMUXUN2wDiY03o9vd7B5HFTHzPt0SSY2ZdZkfPyi/Vg0byaDC54UValJnDHF9cRV/WQerQIf/wEv7G6C1iZwclMSezfVaEzJyK51udxOOkQo=,iv:HSSHcyV7jpRY5oBSGNgFdfbSOwgStF9QLph9219Jq1U=,tag:tKCrhDfIdFcsNMdFZm1jVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
