apiVersion: v1
kind: Secret
metadata:
    name: agora-controller-custody-database-url
    namespace: agora
type: Opaque
stringData:
    CUSTODY_DATABASE_URL: ENC[AES256_GCM,data:ghVzEbruHLc4BMwO6WBzJ4dWGARkPaaV9T7IJVCaey6BODBWBnQTYz8U0vaTVnMUQAKzPWHWW4DKzvx23eyKJL0Q2IZmhjmWEGwATer8y+JZBisxnme+c2WC9DKDajmJG/P6/Q62q/QB3uKGfHqPtrryrd8vdzwq9nbRjEazRPKfkO9lL4Qwxg==,iv:FTWEBAvohZ9xq/L2/tG8+O3ykA3hiqhIimw0XsTVYws=,tag:njC9VL1KzrEQQSekavoGVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbmkwSExOUDdwaFdFQTEw
            RGpVeW5GSTBLSktPMUM2YmVBSDJQb3VxTGxZCk1WbjBIekNPYjcvazFpRFlENFB0
            WmhzUzFEZ1NmVDJaT2hYQmRIZUhaZnMKLS0tIHRTeXJNMGxpQi9FSGRpQnordStX
            alUwVFlrdlRBQ3gyejZGQUU3clcvR2sK2+eQV+P1VqrW8eFfCtz6emZ27S9c/Qo4
            0kl5yMqjylyEBf9KgqG+6yD72DvB7SP1V3/W7vcYE/HbOfpCCEGqrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T20:13:22Z"
    mac: ENC[AES256_GCM,data:fiwKHaWlz8zHgqZTxRNYNbaCPUo/ageqkoSpTkMHnnLIRZILhDni43a6bqwtDuUenlG6vrPOVtUon3Pj2EKTOr891SzjUE1iVsmoPHgIy3BcFureuGVk0MKhmYy5uJVVfQpI/KzuUYDAtrUi85zIQVpWpwKnVzQh6L+crtAzWhw=,iv:5fAbm0YrG93ARQ11nMa1K+hWkhgKez9NAOr6PksixlU=,tag:FMPF6Ee1pKj5OsNTWFasXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
