apiVersion: v1
kind: Secret
metadata:
    name: agora-broker-database-url
    namespace: agora
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:yq8yMSY4HDYfTihg3UzYmHeu3p1HhnoAe8WBmteb1mfqOJ5FNTsntbtbuY+rXHEPvAnsKlGmnQAoxKvPvwc9szPynZQZ371iG0wEsZM/99HbVg7jIbHYcL7tE/raiefkjGqdhBuZgE+DSDdMaxHVv/bh+22LORbtNQaZBIOEcNY=,iv:b9WpMCz8GMqoczR0NgQvrR3Sx7nWGURwYRuUkHldks4=,tag:2emgqEU9zfZonDZk4lHKKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OC96dFI2UDVON3l4TlFo
            aXU3VTlrV0RRSy84YU9uR0l6N28zT3ZwRkVjClp3ZjRMMC81OG56UllVS1J5UEpr
            azB2T2tDZDljOE5OSnd6NGs3ZDJ5NlEKLS0tIHN3LzFmQnlLSkM5S3o0Nm9Sekdn
            NFNRWHFMNEZaQ2VtZGRwZEhrR0xmd2MKyBzv4UcPGUoIEmZEB2kXRaeGEDDhPPcl
            Ep5HdmQNfl06poMYpbl0wi31hyfxtV1umJz4EB9v0gEeluJAqY/tsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T20:13:22Z"
    mac: ENC[AES256_GCM,data:61TQGojCG3ssNct99yEvofixdh0FU1pIYQJfyR+FFOoLk7zm196h2SkLL2/xtNvFJUib2dW4ajRutD0NKaohfLgz1KcXGCfPq7LtGn47NCnrlauAdXtZ2G2tCUCePN1BWtKFkWm8657RtECzErbFKct7rcWGFdT4sxuJO5ZbdIk=,iv:uOYzNZydT5eNZJPsAscdnaGKHj0d4uj95jj8HV9b+w4=,tag:4pYVwDc6bJfZLV3rp0yuWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
