apiVersion: v1
kind: Secret
metadata:
    name: grants-key
    namespace: agora
type: Opaque
stringData:
    private.pem: ENC[AES256_GCM,data:Sm8YDQSD7SEv57mJxUpsaTNDyYqNc47QO19hgFtbintVStAd+Ld++ZH7mH7aEdLERzTvJhvk5tUZtRBP8zsH7Quw4EK8FugXpSRuTzWbUU1/POaOQ2pnIfMxFv8N5zzB8GywMa59oK4MVrPi7bNwE1SBLu5qCRk=,iv:OVOC5eKWA8FL+rVUpXvNKmwcelBMfzEL5e+MzqTnmZU=,tag:21vMGJjdsEMRxJBrJmmnLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZE54aVRMc3JKQmRteTVG
            OWdzQS8xS3JJc2lOT3JrQkNwNFZTZjhuSWo4CmJwdWx1dFlCUU9ML05WNW9tOTRD
            Z2FNdFM1SzdNaXhveFJ1SzladUw2c2MKLS0tIFRaZ1dvRTFBbUJIZ0lCZEJ6dUpK
            c1NFMDV2SldYRU5va0N1cTZhWnhuTzQKcNwDPqPE6pnqrmrmu3ffHpxgcN7QuQs7
            hmir+cCKUyXheajmjEx3SAkUV2bpYDJv0vPhmDBFHQrbcUlHnSFrXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T08:26:23Z"
    mac: ENC[AES256_GCM,data:Aq2NgSzii1H+z628qrqGmS/Se4cJPjZ61PwtoiieYfZFPgMRGI6mRLCWm1btnHP0Xh9LotbDsRfCzpsYSZZXVKu6Bxgpu3NHfKgZObyLc5GbmN9o0sFQQR3n0UjtcL04VyX1bEoyi4Tmoi4N1biTYrggO3k4x31OXgKp1urGbLw=,iv:1ouWXRlr/mPGjHXf7BNAzRzqgYwjtimLW2b6KaDjCtQ=,tag:phO7xxy6fJdDg77/f9yGZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
