apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agora
resources:
  - namespace.yaml
  - agora-web-database-url.secrets.yaml
  - agora-controller-custody-database-url.secrets.yaml
  - agora-broker-database-url.secrets.yaml
  - agora-broker-encryption-key.secrets.yaml
  - web.yaml
  - controller.yaml
  - networkpolicy.yaml
