apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: agora
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:9Fnq3j0EP248Pdp2CYlraCUnpbsEn5a/PaXgpG4O/JTSDDNz,iv:YCvC1f2Lin09/5OicAkRSKquEd7dI3AnfV72L4T3mT0=,tag:82y5bav8aY0slNA2eUSYRA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:N+4z3XovPgR0jOEAIpRwJePcMviuP2xO+RRVbV+4f78=,iv:YAQI5HwkakO0jjx8UGSW/tOI31rmNnDKPSwEkMi881Q=,tag:VX2nselr3lHx8E1cL1S3jA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:mJt6FCabu9jzwriGgCY9rFUYo/QiPq8lVVvEX0jABbJdiUYbBPwO45HTRKY=,iv:bpUVsONmtKvOUoaDmaGS64sS9+qWos+6X7jpWfWfuh4=,tag:SKWrgkOMReNjEYs6pYdRqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaWhQVm5QQVF2cWFXUFFz
            WFlwdFVLQmh3ejM5QW9HUTRaa0Uya2FUQ0I0CjZBZldDTmFoSVNrT2dmU21URW5B
            RGIvQnVsSHJGYXN2U3JqdXZITW1TbzQKLS0tIGFTalI1aC95RkVoWWNXWDcxaGhC
            K0tqbnp1RmlDbkduN204MUlINHlZT3cK1Ms/iLLfEb8KJm5cn7dSImpz1mdw5WYE
            oipMM9i5tAAvJWyPqZUtwj86PT9uYMafrHdxSYQbExx0TDmJUHxhGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T08:26:23Z"
    mac: ENC[AES256_GCM,data:cnpnLMWZJAFDwuJc247+a6hpcoGACna3z9shaeuPF/0qQLEJMSR/hJmeAV+4cyZasKKefWe6FcqviCxHO8NjnfLbKumERnPmbw1tucL3CMalGIbPyGSIvSqezzeiAQ3YdP0av7Ijj7UCkQDD5A9hCqtWOjs4OD5kyPpQJXhrrgM=,iv:i0m7FV0Vml6yfBAR8EdHyXYfXngccgr71PJUqEaO94Q=,tag:wnOsodMFzUM4aI5IfNZ6lA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
