apiVersion: v1
kind: Secret
metadata:
    name: signing-key
    namespace: agora
type: Opaque
stringData:
    private.pem: ENC[AES256_GCM,data:9GBaKZj2g4bMF9pOZ8BU3SR+UHZSIwO0iGOrAlp0X2xW91oF1/ziWaG61gXhy5etgTpehg6xGkPCkvu77RibAjpGqX95tpfpPhUq2/ZIqIcrF4ELHKTUsdoQ+kZUH1BlUBKDAdO6oU2nBB288VujYlHo0Pm8rzc=,iv:vDQOZP4Zg3ANiIIhjbNsP3IDqEioJoV8o8CCCjhxlc8=,tag:jydSJ5o4rQ90kn5Gexm/RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOW5sTkYzLytOKzBCVzJZ
            NWhqbGNnZXd6VE5mSjFhR2k3TlR2bUZPcFhRCmRxWVhVOTgrQkJicGFGbStmUGpk
            bS85UHZkWUZsd0w2Y2RUNkVGSmpvWW8KLS0tIFYycGU4OXJvSzgzYkxKUDNGbllS
            UFZHVVcyRXRmZFdKcFRPQ1ZibThNc00KvGF2N6ONhrN/o87IbNigiTzRiXR25Fzk
            SAp0/9JHEzJotyE/y/BHAdsqQqy9ZqbyDqw74Xt8Yqul3K+8Ak8lgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T08:26:23Z"
    mac: ENC[AES256_GCM,data:34AVMrS+/14/ENrCAtNHNz0xP30YPxwR5glj0tjw4kuzNGoATqgYD9PjVtHCrKOizq0e9MGt6qpgz2aXMzjbboV8lAN0df/5KXK3g+qTsSGEy3viylz8eeb0XVCr+KpiVC9g0ZFgu1sAPXOvIA9CDGguwE3BJNlbguEwZGkU+KA=,iv:dRjFTGWLB+bATTYt3iTYJ5DXM5p9/fAypSPJjkk3Zr4=,tag:pxoFQZm+Qb6whUtDdVos6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
