apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: agent-vault-s3-creds
  namespace: flux-system
spec:
  resources:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: cnpg-s3-creds
      namespace: agent-vault
      annotations:
        fluxcd.controlplane.io/copyFrom: flux-system/cnpg-s3-creds
    type: Opaque
