apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: agent-vault
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    default:
      memory: 512Mi
