apiVersion: v1
kind: Secret
metadata:
    name: agent-vault-master
    namespace: agent-vault
type: Opaque
stringData:
    AGENT_VAULT_MASTER_PASSWORD: ENC[AES256_GCM,data:cRCI/j85vlc/LMat6pf/pPJIJu+Cen6RVnW6Nfb1g6721KUtQPZIlg9woh3Tzwws1l31RXwto4ojXZ5fqORYCg==,iv:yErFIFMrJLpz3SiVFznasOL9CpdpMQUtzlB6L/S4Njw=,tag:JJEiBvfsLLS30p0as0AG4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMjh1aFdpeEZzM3dEWVc2
            YldDdk1QRkF0b3dpNWNnQ0JldTJLdzNYNnlzCit3YjRqK0I2OHJZVHFxRTFUZjFX
            cVpxR21TQ1pNbG82WkJLZExkUjZMZkUKLS0tIDkwY2dKbnhpUTR5QzRyR1kxcVlD
            VGpIR1RReTdoem4rd1l6VDVSWExsRTAKWg+R2Q5pGDEqjCuoBFMFobraTutzyo0j
            RLcVynqa777xXCLOZvrzNIfjqk9OYuHhyqORsQSqxKorCRaJoVgS3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T08:23:33Z"
    mac: ENC[AES256_GCM,data:0gZjDkCF+NWn60CamS/wg1LIvQTPRJg4gPkGvVxjh8H1on/+02/UdCPKG/7haQZ6UyH5NNBYy/h7Q6AcMxxrNvVdk3sWqcigTIZ5gnOG5erNuZCdMpJHTuVmObe4+g4meFJWlwySXWTsKCcPkj8XozRRYQ7DYJqPF50IuPgUw9E=,iv:LGEkgjkgXygO/SgiB364eS3MBWvuBWFreA8IHbWm6ko=,tag:a0wQMU7uhTiON/IkxtXLEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
