apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3-creds
    namespace: flux-system
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:PsYvIU2UHABdn6z7oVTm3q5IYRJNxNJk+kCo5TQ3UhA=,iv:f68kbjaXyaZGHpn1XrG7iV95AlAfPTnZ0/RBIqbGgMc=,tag:t2K9aqiYeiW8tpkxBR8ujA==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/PTy4QG/BRu+B4xFL8gSkySADkkrebRRESNwK0cB2H16qUUrhuHUTtgP7veqMOmcBsQ/c7enmvGpPZjzwJtS1Q==,iv:wbU9+nIglexVdtIlG+5gSinJGvHOtX7NDqr7BTWaTAk=,tag:pCAN6DsJbBTbSIl5ERXy2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBralhZQVI3a2FNdDBrMlo0
            QmY0QWxtNGdzTU1zeVlsVFdtRGpuR0JKMmhJCnNNQXhSWE52SGY3a3VJa0MrVGNi
            cGN6MWVLZDk4bGlnWnFlVituZjJSWkkKLS0tIGJ6OUVCYTEvSk5DZ1NsYldsY0U5
            VVNDdjQxOEdNWURvSDV5c1lOUkhzRVUKo3RllOHEfxUdPq6i95TQ93Cb1JUFP+sb
            6VzL4GgSaF7oWwCc9ZGXMjLvH4C+EGqtHb7NERyxb/m7CVx05/146Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T08:38:21Z"
    mac: ENC[AES256_GCM,data:qxALsw03+uDqp6FnsA/ZSiJZIXyCuJX8vSwWOigwFDvLZFw56X0QmpHUHcnyzwwW1wOSS8vTQPsj63fJd1iH+u8xaX2YpcIuHhNu/LGNfSao8nBXiRbeotnRk1KOypskDOKnKGPtnVumxnw7aN3ifk4EmIX21BYIbUlujqs5TlE=,iv:ODYAwjSdCo7biLFJxsXCwkp9yiwR+KWjqMMW+jC/pAA=,tag:aGrBcJEGwSlpka+Cp0mHEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
