apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agora-onecli
resources:
  - namespace.yaml
  - postgres.secrets.yaml
  - onecli-database-url.secrets.yaml
  - postgres.yaml
  - onecli.yaml
  - networkpolicy.yaml
