apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agora-onecli
resources:
  - namespace.yaml
  - oauth2-proxy.secrets.yaml
  - cluster.yaml
  - restore-test.yaml
  - onecli.yaml
  - oauth2-proxy.yaml
  - httproute.yaml
  - networkpolicy.yaml
  - limitrange.yaml
