apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnativepg.yaml
  - cilium.yaml
  - flux-operator.yaml
  - gateway-api.yaml
  - local-path-provisioner.yaml
  - traefik.yaml
  - cert-manager.yaml
  - grafana.yaml
  - prometheus-community.yaml
