apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flannel
  namespace: kube-flannel
spec:
  interval: 1h
  chart:
    spec:
      chart: flannel
      version: "v0.28.2"
      sourceRef:
        kind: HelmRepository
        name: flannel
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    podCidr: 10.244.0.0/16
    flannel:
      backend: vxlan
      image:
        repository: ghcr.io/flannel-io/flannel
      args:
        - --ip-masq
        - --kube-subnet-mgr
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
