apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:cbuEeAC4Pvx5uo5cF24KavnNfCqulI/xEpePVewXvMTM082t,iv:isVUKcx8ShKEuyl1R7s0Dyzv4IjupcABHQSpfQur3jM=,tag:RO7n+lK78X8BzofK3YyPsw==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:il2TDfHd0rhJZwwu7BiwTool7y/ILpkyvWB5RjhJ4A8=,iv:cZMoDfdKqo3yaNSu/EcbFdtHPKe3OhWghzmULsxAjAk=,tag:+QiZ3JxhmLdckHPgDmLtEQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:EHHSA9ExMpYUjqE6ZHJHeaiZA2TLyn3F829+UkUDpp9qiySZhlB0syNEVMo=,iv:tIIkS5riPg5o5ORy6OzNSCZdgAL3vxyZ8QMiRQrvur4=,tag:4biRGFQ0eC29Rfz5LuZ8Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RGUxSnR3NCtWbmNzRWtY
            U01iZTB1cXFkb2JrakFoN2M1VHA0VytDU0hvCjg3V0JlNXJGT1ZGR2JVN2QrVzA4
            QmJTazQrWFhET2pYMDFKR2RPREtUMFUKLS0tIEI1bUlseXl0WHpiVWFEbkZ4Z1Nx
            Q2ZOdmNOV0NUbDcvWFg1b05Ub2EraGsKpgJgL0OYo8D7oHwhkyyXzSZxDQ48P4Ni
            iTF4UVeSZiWVPbvrCOvDlV1kJhrNnifuFkQ8L06yopt5tZQBuqBNow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T14:08:38Z"
    mac: ENC[AES256_GCM,data:FZIc2qusPtY6LenPLh9eavf4eeLymuh9ezULDoCVd3aroMjHkShP9Se8kA1lQxfEfrVPby5WlNktNXWNfmgshYE/j5rbLpfCyyCJipwlYuarFxvKPxvW7s6F6g9aefjLI7aacK1QgFQM5HYp2jI8HupJMWdfB14ne2Nyt09h1HU=,iv:AL5lRCf/Lp38qUXBNzlbB7aE+k23oZBZcjWF0ddHpCI=,tag:ASCekuwKwIl08stUM3G4HQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
