apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obsidian
resources:
  - namespace.yaml
  - pvc.yaml
  - sync.yaml
  - clipper.yaml
  - mcp-server.yaml
  - httproute.yaml
  - networkpolicy.yaml
