apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: code-server
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:QHB649+21MV56Bbg6ougfmk0fT37xKuYF86D0qXN+1Hf0iZy,iv:FB+WOEOg/fvcUrAO2e6+h+USxdNUZMH9gvXQeRNsBSo=,tag:hTTGS2zJ5XDYM8qL30n5VQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:qNv0YwWBiEOrHIKkuYYLZhpnoe2mHWW8iA8f1NFTm22aOKUtcloAHijrh5liM5AGUBH/XoY1nlhqu+kLKTDM1Q==,iv:wle3VfV5vqmH9TbLXmVkeucjdFLsSdGr7KSiVLQ56D4=,tag:rteTTq0W1tdlQvhernmDSg==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:AevcUoBjOr9v/Z2RQfo5viSDnyXri1RJ+BYw7fmLsSo=,iv:8Q3fC2TX4YdjBLnYOKIThg06onjIumUzQ47iivuaKZY=,tag:0ci7/r2rRZ/c4WszLlZbsQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbzEzdGVPR2ZGaENlZzM5
            bkVIV2FucW8zdHF3VkVhVm9lMTRqZW1FbnhrCm96dmV4NjFhT09RMXI5cml6dkMy
            a3Y3dTcvZjB5bGEzSkJUWUNsY0xnV3cKLS0tIEVUaTU1aVBvOUFmM2lNRzhLMGdE
            MGQrNUVmSHNtWXhFRC9WZzRHYThFakEKYCq/CfvZGw0bUHt0M+259auCHyWh38YZ
            V1vHh4SZfAozNUyKxk0uUAp5MQ+bafxs7bqBrQfLmhYWnLlggVEQlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T21:51:48Z"
    mac: ENC[AES256_GCM,data:HKNxCXjosRzNW6IYPnHYAah+ufHJ59zA/O1+MjLDJRWHgM0gv7wyRoo7xEni0LmuQPZu58BCJTjJztm+Frdswh/RBWSYiK5RFxH5wwnXgiafDwF8gLqv6WZck3gLSEDsKywPvCbIFxDk3LdOOUZTPanvUEcHKZyBFse5lsn8wL0=,iv:iAgR0MJUs1NPaMKyAds8jWxubpxnzwDxZzqNOqaf0vs=,tag:eTqMfZ99SLBzovQzUYmA4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: github-app
    namespace: code-server
stringData:
    app-id: ENC[AES256_GCM,data:Y6POZUle8g==,iv:TWxY6pNJkEdIPandLY9zp+FQSwcxn986zwkEe6r4mjA=,tag:E+4OG+ma+kdFWzdsInoEZw==,type:str]
    app-key.pem: ENC[AES256_GCM,data:h46DY6FNbl+aPAgMwquBljl4YHlsnOA5yHBCu4EiFxuRFuskQZfDIUzkrj3jO8U7yKcp9wq2ooi/OR+0/x//MSNSJCrQhvkUxS5Gu8EctSwEM7rSI5ZQ5rht1XD10pEp7rIWSWXoZqVdblqKqWfAdlkpFTVb4vWHE0q/iqjc4uz6V/OMyzArYNUYtwuw366lgFvcF7krpQmIcjO80v9VgSGVhKy+htI7bbKbY6CVB7YqzHQKr8OORD5vGY0QFQVPQ8rEJX39o5Fk80yGx9OEwXTCzZB06giNSjJIR77TlzQdIceXJrcrzatBn0be9R9VKVgS7yRDzxULW6Od8Qzk+6bT+uukt/T9RVR4GmAQheFKi647jMPaZH3954I8I22gtw0casQyGgqbINuzDgVRCnzNf7hRW/Xt0D4oTMY9b/cOj7eWtWpycnoaIfFeBTcPxrAMj7cnQfu0WoA3KdUlE6oaKrTq0DvBnbY+8I8oPrQeNmL3OUOw5ndzn+c33a5ZwmqSfL7pGIdJ+uDAdC2lUY/DtX8Ne9c2mSUmNlt83Yb/m6vXtL69SdoMd/V+WgaYuC6gWywJzx+W7PcVhOeOBkG0p61cU83kbqh4AvpgswEKoIUXg71y1qsKDBqe4Ywm8hmo2Sbd/WR6BerY6V0VHdMbqpMyKny50krL3myG+aelJ9bu0T8KGlhNbnZTrlw0BcJxDrOty8NGVYb+XFsbLEkHYvpcVSbwTrGEJByl8MyrafUjxP63zWZ5Mo/ig0BGxLihcldoa/rDqJYgsQZAR3yctvFtAbiE6MZLZMg8R+/nYMmrg7Ck0FYLE94P8DExRmk6X4A81N/yGefkno+ilSspOmFrmHgryUg5YSWZN/vTo6OjIexuW9efMPk1KG1AoxyA4CpaAhe8sXlbJM69KOmWaLtKIw/MzxCbezGd40+JMl4syU3rsbMjbYyxiA5fX3yXK5Db4Qht6kJbm1uSNkQXOfX17D9P3/bEWt46Il2Pf/EMMZqCVziJGDJdixuzt+TjTwh41i+R+G+IaoFPAmRhGMqHBsHKv/rBaEvkwIi9nC7gqWohRzvfIk/7/raVqlTwsvLfWXONr+adGTRyQMnPauTcoe9UfdrmuDUoAhUAZG0ozciBAacEN0898rKMgdd5jzRmGvqh3Q5RV7ZRs7svuJFTjUi9B6GnMN9TREZj2fFpN0viBuGKX9Gqx9XJ1WlsnSfTQYZHT0AH8pndysqWOfXPsYnItiygQT9SD5W+PnyVv1uhiwNmnOmdzYuXrnLAqdJGVe3FVU6r6v2+cruxT6dOGxGOLRa+2Fza8m8BHGegSMXFBnC0diK72JOE7/a/hR/IRGMYXnSvemt0wZIGAv96GMSEGcn+X0GW5PkQj/3NDt+iqAAc1eufx0RLUTINnt9CBxjeb41ufvXzQkqQVK67YeiNhd3GtOFKw4qb+7iT2sfhqXiOFOSIBT4pQWnfnnYbNkY2MZH9EJ6nuV2tWhuYQvLwsVxfSHgOs/VMWAVUU3NuLpi+XAW7TVLKpb9LE8U7M9j6qWbZiW0+SD92wqZs5CzFnm9BZGNmL6c+onBZdSs9wOBFzTG31hMXEfvXE6wHh7CvtStTgP6MxV+NgVKxKV/r2IPMCXIKPjuE15rmTGfqkUkQG3fWuS3VUWU4+FaORBJNujJ9obtjbrHUOrtPAoxnDDhMBGQr4F7wBpIpMDePZ/S3JpJhfRaIYlqRFZDKSxZLZhw9lfZZBzcvS7xjW5wxr29r6bMiAPUq5xxOczlQsnWYYRZr0dTGpl0mbuJKv1pTeT3RgFfO5hA12OjDI8iJmvPMKH+wKOJ43V6kLJmQOPqRgRMK4miKQE1Ke3vEDdmYDgt+DxdISZsGSEzY+knUGfZCErQ8C4bixUwguG0yUeeTjkxLYEO37tzy5c9WUnZ0U2EJbZmVCdWVc4pAMiB1P/fZKMPilDhqeRNmq4nQT3XVkmJnGJvfiZncAakkpICEV9X6KML3m2QWgW6Xj7hxVqPqHue+zXzeDy202cee/zLmD5kkpzI+S46UgmYHAvnOu3L+WOEINU+WgaWa8kp3+CP4NZbt/BlLulcj2atrIkAdGe7SyZg5IkWLx17R4YRduFlhBTyDQU3MjPl38NU67oJ9aOifs82yK5l9h71fYijfVa40VCvxc6PtejHTkdqwXNhIck9z1NP+SFwMvVj1S+JszDcvZXtCa4nxzYxXZ5iA+g==,iv:WLnKyi/ylDjcvqMhcEIQpOx1R8g1L5euE9tcp0RyrPU=,tag:kRKu2dug5KpNSLLYV2F/Pg==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbzEzdGVPR2ZGaENlZzM5
            bkVIV2FucW8zdHF3VkVhVm9lMTRqZW1FbnhrCm96dmV4NjFhT09RMXI5cml6dkMy
            a3Y3dTcvZjB5bGEzSkJUWUNsY0xnV3cKLS0tIEVUaTU1aVBvOUFmM2lNRzhLMGdE
            MGQrNUVmSHNtWXhFRC9WZzRHYThFakEKYCq/CfvZGw0bUHt0M+259auCHyWh38YZ
            V1vHh4SZfAozNUyKxk0uUAp5MQ+bafxs7bqBrQfLmhYWnLlggVEQlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T21:51:48Z"
    mac: ENC[AES256_GCM,data:HKNxCXjosRzNW6IYPnHYAah+ufHJ59zA/O1+MjLDJRWHgM0gv7wyRoo7xEni0LmuQPZu58BCJTjJztm+Frdswh/RBWSYiK5RFxH5wwnXgiafDwF8gLqv6WZck3gLSEDsKywPvCbIFxDk3LdOOUZTPanvUEcHKZyBFse5lsn8wL0=,iv:iAgR0MJUs1NPaMKyAds8jWxubpxnzwDxZzqNOqaf0vs=,tag:eTqMfZ99SLBzovQzUYmA4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
