apiVersion: v1
kind: Secret
metadata:
    name: agent-vault
    namespace: agora-lab
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Db3Yo2096BGCm0udHarCY/PeFX9vn1fcrv7iqQyZxkCCJH/FTat27qAc8NoRRT+3dBXr2ipW0p6UkSqxIxFp354/YUdYj9g=,iv:yptKMRgEfU6j+I0GclvBfmKAd8bePabNrYh82gWS6Bo=,tag:mhCYICP/l/1BIwZxU43yvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMEs4NERrcGp6cXRLNlJR
            ck1XRnAvekV1YURFRE12WnBtSzh5RUM4eFNzCm02VWlFdDRwVVFKaURKaGkxNGZI
            Ri80RDFVWEM0NUhzU1lBajVMVUJyakUKLS0tIE96TGhqU043czV3QjdZakJtK3ll
            NzVaZ0pIVnZzWUw2YnVSUmlOanFNWUUKZyYfeXkbmExEhmWEjwiFYkKVABaCSYGN
            G3dQcZAJJ8gcbR9I4PuRsVqz1CrTw1f8pm1VH3POA/G1pF5VildGUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T21:26:54Z"
    mac: ENC[AES256_GCM,data:IPojfbczoeUE6oq4yT01kSCKwzy1g8r77de/j1wKIldaczW2JV1xU30wRBdJ5YU4aavpbEmHDQV76TH0eLnAy1z7sOvpX+aN6K5soiTsVWhORwM1hHli0D0HyGqYRlLu7jjJjKYRZR2XyMG0BlI2lcaMrPEEL2hWuGN1vOeJDJg=,iv:Z2Y0gjlHUHwmlxTX38J2OhPw8obAsZ1gEhjmbcy8SA4=,tag:eWGTDXOQCrY4suZdhaEPoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
