apiVersion: v1
kind: Secret
metadata:
    name: grants-key
    namespace: agora-lab
type: Opaque
stringData:
    private.pem: ENC[AES256_GCM,data:Sm8YDQSD7SEv57mJxUpsaTNDyYqNc47QO19hgFtbintVStAd+Ld++ZH7mH7aEdLERzTvJhvk5tUZtRBP8zsH7Quw4EK8FugXpSRuTzWbUU1/POaOQ2pnIfMxFv8N5zzB8GywMa59oK4MVrPi7bNwE1SBLu5qCRk=,iv:OVOC5eKWA8FL+rVUpXvNKmwcelBMfzEL5e+MzqTnmZU=,tag:21vMGJjdsEMRxJBrJmmnLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZE54aVRMc3JKQmRteTVG
            OWdzQS8xS3JJc2lOT3JrQkNwNFZTZjhuSWo4CmJwdWx1dFlCUU9ML05WNW9tOTRD
            Z2FNdFM1SzdNaXhveFJ1SzladUw2c2MKLS0tIFRaZ1dvRTFBbUJIZ0lCZEJ6dUpK
            c1NFMDV2SldYRU5va0N1cTZhWnhuTzQKcNwDPqPE6pnqrmrmu3ffHpxgcN7QuQs7
            hmir+cCKUyXheajmjEx3SAkUV2bpYDJv0vPhmDBFHQrbcUlHnSFrXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T07:12:14Z"
    mac: ENC[AES256_GCM,data:5jmhaEiFA9etHm/yojACjj4gpieqEdoDkzs9D8KfVdO8J2MxQdM3wuvnTUFOuXvNFGb6xhA79R69K2TGewGV5BsxKJPMFu7kQ9Xlfu2y/8ESCRlhGAlbeK+06nPryxB8CaPs/GCC1QhqwinpXOxZ3zOGSLYHtWac76DH4mef+Cw=,iv:8pDFOVCAXcleVaRPXLJ6DCA0w582+HpB85Odpam0/FI=,tag:+UNYpjOVRYuzf3LYSg+8Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
