apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: agora-lab
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:HWdU+7O6DIUoouOzplnQMXhUCj4CedROQlQbPSrCoKDGiZcK,iv:NZVvtq+1VATf3Kdq54uha7F13eUDkStI1644y/dbqDc=,tag:NWhkUVcVPQNgdQzXPKdBwQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:adnWSMHNZycUoftmvRsPrwihrHa+8yRuCdnHobYTyjg=,iv:GyVchy+y42TUObtJkubc/NOFvp92HTwgq9uje4YpK00=,tag:X8cmYKmlaQqgWfI4DiholA==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:/ZTLMN5SOCiledX9D4UuxQzLslTN4fLKLK4FWtTA3ocAIPgwdCMWpnek9E0=,iv:0wEFcEcFbhwpK9Ju+2XvVNevURBqpQDqJNNd1zE800A=,tag:/Iv/baQolCgoABKrKUrTjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaWhQVm5QQVF2cWFXUFFz
            WFlwdFVLQmh3ejM5QW9HUTRaa0Uya2FUQ0I0CjZBZldDTmFoSVNrT2dmU21URW5B
            RGIvQnVsSHJGYXN2U3JqdXZITW1TbzQKLS0tIGFTalI1aC95RkVoWWNXWDcxaGhC
            K0tqbnp1RmlDbkduN204MUlINHlZT3cK1Ms/iLLfEb8KJm5cn7dSImpz1mdw5WYE
            oipMM9i5tAAvJWyPqZUtwj86PT9uYMafrHdxSYQbExx0TDmJUHxhGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T10:59:00Z"
    mac: ENC[AES256_GCM,data:v7fyLPoQlQqVjj5M9t8lUo0UWKzaf1ZTD7OlwvvIYbb6V9Llq2tvvooOS0fMNEHoVAm/1it6q9g5lHNnVAUPxwBwjMqveKyX2rgT7jNxeW3YeUEVFxiN1rWyHZa/fGEW5WfKM7QgPtbD/mbhiBZwf3oDYHSKUhwhE9pMdQyHMh8=,iv:ZBCpg5kyAbM3Ee/A2mbr3Y2BViCH86h98yCHonnkkV8=,tag:sEIiH7RFhYYD6e6SPzucUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
