apiVersion: v1
kind: Secret
metadata:
    name: signing-key
    namespace: agora-lab
type: Opaque
stringData:
    private.pem: ENC[AES256_GCM,data:9GBaKZj2g4bMF9pOZ8BU3SR+UHZSIwO0iGOrAlp0X2xW91oF1/ziWaG61gXhy5etgTpehg6xGkPCkvu77RibAjpGqX95tpfpPhUq2/ZIqIcrF4ELHKTUsdoQ+kZUH1BlUBKDAdO6oU2nBB288VujYlHo0Pm8rzc=,iv:vDQOZP4Zg3ANiIIhjbNsP3IDqEioJoV8o8CCCjhxlc8=,tag:jydSJ5o4rQ90kn5Gexm/RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOW5sTkYzLytOKzBCVzJZ
            NWhqbGNnZXd6VE5mSjFhR2k3TlR2bUZPcFhRCmRxWVhVOTgrQkJicGFGbStmUGpk
            bS85UHZkWUZsd0w2Y2RUNkVGSmpvWW8KLS0tIFYycGU4OXJvSzgzYkxKUDNGbllS
            UFZHVVcyRXRmZFdKcFRPQ1ZibThNc00KvGF2N6ONhrN/o87IbNigiTzRiXR25Fzk
            SAp0/9JHEzJotyE/y/BHAdsqQqy9ZqbyDqw74Xt8Yqul3K+8Ak8lgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-27T10:58:18Z"
    mac: ENC[AES256_GCM,data:7+rLeysy9pgmS1LKrvwbNtAi58p5JsW74FDn5Bc3SrsSl6zrPdpOBRKiS/dhRulyZJeh+aJEYVRg59L3Y4kwV+cabBb2utXfO76IvhTuyhzUCPGRNZ9PFzCwUI6ca2AuVWzMFG+qvs1QIXkYLZ9YNH9kALP36QQjqS6KZmcL2OQ=,iv:kI6Pa2GdLPH5VRCmYZ/NbfHppinMQdZ3pyVQlxyL550=,tag:QBqVIcYEok9PJ+LWqAgPkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
