apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:0T1u6cuNwcyIJMQERzUGkqovIiCuCRAqbTqtEC6eIBHAOFXs,iv:G2L7GXtm2pzy7mJ/QJY9UBug4U8yVAvA4KxA1i45LYA=,tag:efkmzrACikSMfAsFyG0SMA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:Y2BtIJNQtt3rTJJHXERCKCEBUfbzHnBR4G4HWFwugCY=,iv:vvLGo4wMSg1glb4PHYjnaQNAGgR5j26ix/6dWjo8OAE=,tag:MmVrQl9+w2WEUC9de7aCYQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:SZHboNek1c6NXHi8iDYO20RiRvDfKy56Q1TbCaLwhVquJIq/PhYSIBLEFOw=,iv:vVZ2MAtYv12f9F2mYGSS9pc/J6jPVMbOC28qDjcf38U=,tag:SYe8MsdMBjLLCzLS/xwHvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L2FtMm1jWnRtb2dqNnBS
            WWV3SlZqRFlaZTQ2Zk9aaDk0VlkxejBpWW5NCnlvdjFJeStzbFdXZlRRRFpBK0Fa
            YVZwTlRPWmY1UTBUZFpHZm1MTFhzL1UKLS0tIHRLVVU1NUZ4VnBmWUxuNVY3OXly
            Q0pkRVIzWnlrV0NpN0xPcUVYaTF5NUkKbg/Mgyc2OKnQ+iCCqpsnvQFn5t+/4/bo
            bWMLbjbS88A4laZvQEQFRuZ5g+fl/cvFSLXy1PdE+CM8ZTkwzJ7+2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-07T13:29:26Z"
    mac: ENC[AES256_GCM,data:UENEy8q/04KwZqQlviGEvhT+VziyK29HHgwj04vHUX6TCJOb6fezyphiGSJ5NKPfGZk3o2G1Ve1tUtGf+7diJo11w0Zl/aF/R8VjhkUQl6iADA53/6VpoKwCKBQpG3z3wiLy4gApusI3bX+ALbJ8Bt1FkQEkxGLcqok+8tW8hgI=,iv:5EiWwGJpYaZofqkd1eUQlVw2SWLhvwmRkUyT4iJ0ZHQ=,tag:qdDTegM0yiLnhbW6hVcrBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
