apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: stremio
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:nB2/FWAoS7w/lPpuhH7+gIRd3YuEWoUEDmTxXaXMCWrARbHs,iv:e3nVBSnguXfibUE+BjS+L0+d4uN944iALm646Jq/iHw=,tag:ezsw001zK698KlRwAwUaAA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:QXdM4VI5U9Vv3aY8+C+FX1CH4+jKrkK4EV/Bw1EUMNw=,iv:yZZqbzqMlRP2dAtJMJuyHMSHQWeNTyTYwtjOfETb57g=,tag:49KVI8+w4AsxpHpNoSYv+A==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:NUm9drBjswOnlmTN1bba9JvYFKfXlf+94o/oNrHC2KG/gAetKUqdKffKKA==,iv:zhnkB0BFQMuiYmdvvTuehezn+AERcmKmH4rOSJ5y9bE=,tag:uG8+CYraJUn5JTLRfz5RAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad3lqTHA0QzlpMlhQOU84
            QWdOd0I3Ym5EbG1rRDc5YjJWZGFldEducUJ3ClZrV2hXQllOTlNScStOMW9kODZT
            cGN0RTRka3A0WStYOFFyZTR1d1hDeDQKLS0tIHoyTVpDcUcrekM4QmZvaFhsYURO
            U1hFdTcrbVlVS3MyV2JmV1BNRndxSkkKzen5sXYCL0WjRm1vlYxvRusHDzDE1Tdm
            SWRCOcAKWN73WsuZnqW0pMOMztMQGJJnJPVRg1H3vbFhXbO02xc5cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T16:44:07Z"
    mac: ENC[AES256_GCM,data:6j69fj4ad2u5JxPKUsmEVbn+78VY+UufSkWE3E9w3kl0gjqS+dbNj/pmx/WE0TuH6QWqibh/uAyZ7Wd0s5i1hTyJfP5WwdoVGyEHRzoqR9GrxIUGWhZPt4BJMX97RTu5Ap88UCt2tmK+QT/EDXUUbGpbmv4Erdj4+VZTAY63yBk=,iv:FMJzmDygMySwaTugAQWoDXFHBY0P4a9CNy7+GdGbuPA=,tag:42d7hOJabMFz4ohhtyPWrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
