apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-secrets
    namespace: stremio
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LT0ig1XMm5O8ePLUD+5GiDA+cyYzVLOP+sHDOG6CH+SWAopo/a8Zl6CrDlEKsLwIIQbNoRbuzFI+TMSdo/5asOAl,iv:G0kAoseuEgJbpE7HlRn9Xl+4v3vQ/INFl82sA5aqpxc=,tag:0HxluA3R/Z51ehn1PIOQBw==,type:comment]
    #ENC[AES256_GCM,data:SEre7Qy38SKyTWiiv60J3124XwJIBQf6f/3jM+zXYjjBPFotdwKpA8M6YnE5fH1wpxPIXcOt0lJ8YA3+ZS0m/Q1CatSAEqQ=,iv:2HsD+PlbCyZVXZ1Rd/xUlAj4RcSlgFaH+lGFFw90FUc=,tag:Ckt32+remKkJa6Yghs9M8A==,type:comment]
    SECRET_KEY: ENC[AES256_GCM,data:lqYJoqdjcvKmbroTOrY7CTYJQxqFTGA35jxqwwBkAb4Ry++tsq5Y6/VbS3OJrkA6+KTV8hknwBrbejePDIWD2w==,iv:mMGPQy1wXTMx3E/yIQmZcAinJCs4Wa5thHc/+m1LduM=,tag:YaS1HSFi8QSMWsR/UfWsgA==,type:str]
    #ENC[AES256_GCM,data:Svz5PlEdlUrmoj5QI6WkKEtDhrXSFB6TPiANV44RtSKYTpshJETR1VZt0mhKi+k6fP6dXnv/27M=,iv:xPyGVKo49hCC4671EHoByu6pCAI+WwpNN2iKwbIuj8U=,tag:s92T0JGMQFwRkjYHk138aQ==,type:comment]
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:X48mBfxbpYC7hKV8Qdft2psbPvHYIBco5fAk0eKyCP1j0oe1Q14YyNhdh/Ynu48i,iv:fDMPT/Kb9GzBVv0rdGwV5Ap+Ad+2rs7XhGHnFVwf2A0=,tag:XxbtwHjs2o20uQsFacNVvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZFRxZFhTcjdESE9VSzhh
            cmdFUlNlQW1JeU56bHZuVUROVlFHOTdjWnpJCktlZ1RLRUN1VWk2U3JPQlZWZVhT
            WjZDVXZZaTNYMDEyRVptbm1VNGxJeXMKLS0tIFY5U3NsY3lsbm4xZVExNWx4WUdx
            eXY2SWZkVmxiRUt3SXgrUzZHZmJlcjgK88GfMXUCLKihMS6BsoezAkS+za6xFAO2
            NdRSlgS7lVGAHO7+hrvLAB1pxPV95YhSZk8Fh+Z6DfB+NAmvAOgqNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-29T19:42:40Z"
    mac: ENC[AES256_GCM,data:+8IxFopEFit9Er8LpQ4NraxXTuDzMlD//brf5bHjC1l8yt5UqjI3/+3Sq7v9/kUAJLLGkazCm69KV6od5lJwIHraLDAa/bMMfAC0XHMdg+TT3TXSS1YpYuLc9lOv+2lzuMHTJqf11RGKwpBBxFvYjkkbOqe+SJkY2CR1xytytQQ=,iv:HNv/+M/c+RN9e9FI7wP3Sa2zR1plrcvtXmJg5/2dCP8=,tag:Y2OPE5t8MGAqsoaCz8lR+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
