apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-config
    namespace: observability
type: Opaque
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:CA1u6sdBQQ6E2x3/A0HYDbUhPyiiHM6CMoIeSKXJgePRMoUd14+FCq8GUuA5670Wx7uUTuxQkeTIIMubzf3WZi99yP5RzPoB/RFObclUFUvdLYcs//eUcYwIv2IPZqkVWC7pHzkROAuGYW1xEQGoLPzXQSjHheaVeu43ndW1h8vj0NFJi0cx3aCSA8W7iRL753ynKNR+JwIKlPsXDFSeddakWfkSViEJgF9nYYFdQwB0zpohMZm//prl89gCgkh8Rw2kWrTxobJaC9YjDEltnL+O/PMUGg1dAAJJ9mfmvJMwlxSlPgPMuyYFWQnf73bvtwUsuvh6P1hWYH3A9vVqxZsxxR887bI+I0uJEFVqnJWJg+XRIVvcvaYZESi9v4hZ4voM/1wsn6Sda1aoLx47iqGFAibDUFEuRzTnzf9zmitOc3qv5HfzJlAWFC3LvtjJjA2f6ZyYBCrGsRz1iJOMFfnGzAIwiU7fPNsbqipuTK6qZjZUfZmCKNKZdJm2Qgszz6P3Z8RESJki/9LwR58U3+56mVLbaSCEjGyDcYnhmRjvbtizUk3IyARqLg9jQuWiHppPKye+eKDo4GJfsG9SXvL/IxzGrJ9r2NC8S3oGTfH9RjGPfEuW9naIdig+lDptwgwrYSwImiSc0JMcUSOKZzJyazxXm+xSHEUKYx3T1/lX9KCq5TZgk6VE48spj57YjyzkcYovd9yaFH5CytYG22vRMKdpNrgRM+QlrPgJR5u7YPp7amAwb0q4D4HRAAjFYtUt8nPVJRjeNX5IH6rlNK/He6EQ1HB9qDZLJ2DwT6zDWNCkZwHP8nYP3Z1tsNsZVtESSrchK6xdhOXddb2w+THvxtqnQDLCZH58vno14cU3mvgt3NqwG9cZog+RakbtEqWz4LmXUP9Y26NvB/FT6Hs5/AnjkUhxdnDp4lcWXz393DiE5Kxcmg7B6Xd71Z/XVQo8HQEgUTSt8o96+H123VoAXdISkBtG/TTo5SUMFmDBnIPqhzk2h4CV/cyQJ5ncp0H8Dij4L3P8tEop8M68ifWs3PxT97znRxajKFTlacXAb294gwy13x9tUiDXEUd0ybrirTkbhPjnXFdjs1Qel7VJCebsZ22gsJaSxS2au9VwM8cyxLt+OBNxrQ3N2gXxnVqcbAzWqR289WpIJffaXHuMoN7FA5u7HZvWcH/peXhqv9zzCUj8PoETE37jUQQIDxbzdbDzRo39pfj8WYH91mnqOB8fNDzbG0Mg365mc8cYKGfeTL3ZCtEcS7OFTKkk3lhi2Arf7Oaw/hYIJrnJ5992BjiWqRXUmF2CTfTMNFt0sPpWn291PIYa8CFVJSbgIxHM0gOTuC0UtWT5X1tt7Pn59xm2zQl5W+Q9m7as0WV9gBErd+xJCyIJ+n3GS2F8Yq2a1G46R2Xd9xKUGHIqLWP4V6XbJdWX5G8c2cUOdmfeKdqCJTERU5al0f/RWi1q7GSRR+TqziBfSMomO6WGBy7vWgv7G6rEYQBIuSUrV2fEt0b07FrhyloaTrQY+IsJs0aSlJIWp8d5F8+jtwfGaBgzY/5+tW0sgJXKH5dbRLp9P2SK1lGz4IdO5VDKCPa60rBt6FR8RAHLoiPvVVbIcxKRS+k5M0R20Vwzv7YYFZzrJk6KlvC10lRXEwB1ZWUYt9mWBHXYg7lBTlnnVNwZmzzqJUM6QmWby7cmmRmMJPEWjH6TdJ1QySB/S60bGjFfFRQB1ImsriNebgAjrBS4Wh0H3OO9pAoq,iv:rR9qx94XfZhrAxLWctg4mLS9zM54tT/JlEpDw2pOQj0=,tag:OuliQaiIUrf+GBaQaGdSig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNGt1UlNLN3FON2NMWlhX
            QmhYb0x4MG5RZ0J6MkY1bUZzL2lmNTZxSkRBCmRGZ1dBN3NnemlYTVEzTWltSTdn
            N2x1S2dnL1d5djI4YnhCdGx2VGhVSmcKLS0tIEI1K09YSjJvaUt0VlJNZmZUV0ty
            NU9jeC9vc1ppTWtYdmlqbXprV0x6RlUKHS8IfpENrlec57V9uqdnR1e3pFssWF5+
            Jbex53Fe9SH0d7PsmFfonRPGELhDwqlOoZmIF0Pydjg697z9nR5lUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T09:09:44Z"
    mac: ENC[AES256_GCM,data:vA2AYyVfwW9xdl40kr7uXs14p7z2tUAwG8+nmjISvE+oiyrg2Ga2CT1AFf5FZDhyV/I2nPrxWFSQU/SUmwSqJAP8eyHsJGon1VIg1/nRcw1NGtSKIt8OHMxk+q5+5SNErKW9qYScM9n/KTBKyAAII1Ymej6ED8BK3kCeeaf1QZw=,iv:5fSlqvK0XGuNk3d2oUeaCdJ0OJkrony7v/OAtfRs18g=,tag:N701evnkGFLLQXspSLXDNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
