apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - namespace.yaml
  - secrets.yaml
  - alertmanager-config.secret.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - alloy.yaml
  - httproute.yaml
  - monitors.yaml
  - rules.yaml
  - networkpolicy.yaml
  - dashboards-flux.yaml
