apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:0XfJyyA=,iv:a29k22ZCCByWFLx5K21aTx+QVO+GPHC5k70a04OY99k=,tag:8+sRdpGhBfxM3sZgNnyD/g==,type:str]
    admin-password: ENC[AES256_GCM,data:BoGisnV1eQL8jSUKAYeBett2GcsMiADe,iv:qyXUz9nYe87Qb45POCzI7JHvnEK0+DCmPrAGvdq0gLM=,tag:dKMqMcBYqyn1uyxWT97YRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eFU2elNSWC9OVmJtRXBj
            anJmdk41bGl3QW1vQVJhUitEdDF4TDVPMUhZCi8zczFjRzdYa0VqWVVZcDlJcVQw
            THc2UkRaOVRsYjdScW5GSGgySXJTRHMKLS0tICtuRUtDdTVoWlJ5UVRac0p3a0xo
            WlA2S0FteFF0UTFpME9PVVZxRjd2MmcKVAAjfmme/TNbHecRMVL4yMVgEfomz/kr
            Qp8WH5FA2bDQ78PeO3LJpF0jeqsRQF6YcszOORS2shh9+a4X9aIWbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T21:33:28Z"
    mac: ENC[AES256_GCM,data:pHL6t7rPfplwIjVgZo3aM8CRVnJuaU9gerX/sb6UxS41s0pX+onInJfuvuAuUDryTj2zvpeXoymPhFg8sa+snf5tC1Dz04eLWUtdijoa3D1lEyJr7sFRGUWL4wqc2eEvkmXRY2woGXyjUthO0BUXM9cT/HV26Zgp+BibgazB04o=,iv:a4qZRh44oCBUlQdm04frbz5ZVZfmyShdyv4QWm9GyZ0=,tag:BxVHqJQPsrPKa6Bqpn/XkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: observability
type: Opaque
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:TvfOjZo9DbZeNzuIJPBqFf+Z0sBCzb08raVmYAGOfv+u/cz23tu6y/DJCoxyiqOtC28g9GvTfwY3cM7ss7k/ag==,iv:pbym76NhYZcRihXbmAH5BRAPQx/e2kIXzz1dDFf9N9Y=,tag:dvZ0mqsj+zFEO93naaz3tg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eFU2elNSWC9OVmJtRXBj
            anJmdk41bGl3QW1vQVJhUitEdDF4TDVPMUhZCi8zczFjRzdYa0VqWVVZcDlJcVQw
            THc2UkRaOVRsYjdScW5GSGgySXJTRHMKLS0tICtuRUtDdTVoWlJ5UVRac0p3a0xo
            WlA2S0FteFF0UTFpME9PVVZxRjd2MmcKVAAjfmme/TNbHecRMVL4yMVgEfomz/kr
            Qp8WH5FA2bDQ78PeO3LJpF0jeqsRQF6YcszOORS2shh9+a4X9aIWbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T21:33:28Z"
    mac: ENC[AES256_GCM,data:pHL6t7rPfplwIjVgZo3aM8CRVnJuaU9gerX/sb6UxS41s0pX+onInJfuvuAuUDryTj2zvpeXoymPhFg8sa+snf5tC1Dz04eLWUtdijoa3D1lEyJr7sFRGUWL4wqc2eEvkmXRY2woGXyjUthO0BUXM9cT/HV26Zgp+BibgazB04o=,iv:a4qZRh44oCBUlQdm04frbz5ZVZfmyShdyv4QWm9GyZ0=,tag:BxVHqJQPsrPKa6Bqpn/XkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
