apiVersion: v1
kind: LimitRange
metadata:
  name: preview-limits
  namespace: preview
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 200m
        memory: 256Mi
      max:
        memory: 1Gi
