apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bretagne-preview-wildcard
  namespace: traefik
spec:
  secretName: bretagne-preview-wildcard-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - "*.preview.bretagne.dev"
