apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3-creds
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:eAQaV8Zvx8fJHneKCAH6u43ixOFffPZtHt1kkObrb9E=,iv:grU2giztsj52jqSU7zgHebQ8P+6Yms+CDAgIEZ9AF5Y=,tag:3dsIcwRaNPX2SVZqI39Z0w==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:68OqrAQ1ZLe8+p4KXhd2bZvKSnmaHL8HcOu9dBkZ2vj3lzKGfrpmTgCH4hRZeXxZX6dFHIi6K4cuGuSOiwoG0A==,iv:yjiBryE+fYCf7MqsDRgcRcBRD9Visw/i5TRjoliGxpo=,tag:8qOuzh3W+mP8SWgUG2nEfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS1Y5UUVHRVlDSEVYdWpq
            c09Hd2NuOWllcW9QVWVXOEV1Q1g0UVUxS2s0CnBEYnd3SnpYY0doaWRWYXQ5aFRk
            dk43WlJHQmJ5SENqb08xMXI5djJXS1EKLS0tIERMUFVxNlhZczdVMWRSRjU1ZjRx
            cHFYU3MyRGdmY2p6K1dZMVltdmYvODQKfvBFOWsodclAieRUw4CGKJ2Tb/L+lt4w
            sRhCOLPx9LaSetaPLUcUlbajVBeir9DY+ammoUKIfuGF5zUzl9+6lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T17:20:10Z"
    mac: ENC[AES256_GCM,data:UMz0rroqJh34CYdf0BC3Cpzp6f2/ZzxCQW9MghSN151zXSZX1juVCkFss4uadag9evyXbyYXtB7O/QQ1lid35JcXbKEqgRbewqrjhUzEgNjm4JmtJwbGFttJll2Owc9p4PRAPlcQym1icgIUOzJCi9O1xgm8CUdBxjY6KwEU2jM=,iv:KTXdUNzatPM+m2OGuTRfnM8YqXKnpejphb0c0MVzsmE=,tag:gXIhp+6/6Vl656USGPn/gA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
