# Self-contained SOPS secret (was an empty copyFrom stub, but flux-operator's copyFrom
# never populated it → Flux re-applied the empty stub every reconcile → backups broke
# 2026-07-01 → now. copyFrom abandoned for this secret; ADR 0012 to amend). R2 creds
# duplicated from flux-system/cnpg-s3-creds (rare rotation, worth the reliability).
apiVersion: v1
kind: Secret
metadata:
    name: cnpg-s3-creds
    namespace: pocket-id
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:GMpfo36wrhQ2dlpZvjXKvmakTauEgLzzBPCujo5vyoM=,iv:v9iDXmMgWgdjgcn39xYZGoWiavisUEyrYRlmUQ6ABiY=,tag:Btlnyw1QgBzuLyXbCvvziw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:O3UsqOckaETPdGTk61HoH7U2YAoKOLrXzmHIQVPFXtWT3hMk3czJQm+bUzYXmf5fKQgnAslN1dRxjgxh49G6OQ==,iv:CJYhckVU7srAw6EVE2uWbvzAJ9qiugYK/S5m6Z0uUhc=,tag:b+80Qvdwn+H5+IkVe1rejA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWFlvcFdQUXlPOElGanV0
            bDlYY3grZUxsUTAzUjNHRlM0SUd4SWdqSzM4ClM3ck9lRHQwVkwvbFJXOGZIV1d4
            ekpHRjNITGw4Yjd2SStQRWxRSGwrazgKLS0tIGo3akNPS0d4ekp2UVJmR0ZLSE5T
            NjdNeUJFdE5FVGVwWHp5QUM5N1R4NDQK3LGHVuB4el+R4BK4cehOjCXsZoNmG1SN
            N4oVLYT50vKho1v6Cy/J9R+cmxTTNA16LED68HmFAeddvBv1jMQLXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T09:27:01Z"
    mac: ENC[AES256_GCM,data:6GgBer3Fj1iaNIWnvJACqq/CwhdjCwtVttRf1eyb0+Jtq35n/GHbubYae9IkX9Ijml/bwv9ZvjvIAkVOo3L+kjVg9N6qppeBN2+2Apkgm4rsAeslG9kG6xhPXTpiH7c0GKEGBtbcQWZ23mWBvIyHOrY6+AyU9AD+2cX6csd3ZTY=,iv:yNDsN3Ix/3fC07we9NKcBYlujr0Ez/faQ6CYxxkKaLQ=,tag:f6QluZlnVBwgwy2IATHzdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
