apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-id
resources:
  - namespace.yaml
  - secrets.yaml
  - pocket-id-cluster.yaml
  - pocket-id-backup.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - ../../infrastructure/bases/cnpg-s3-creds
