apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: pocket-id
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:Bh32ES3pIpoEFWUiT6/1JPQiIqgs29HpUryGwUzp/a+yOwwaUU3fXBX0I6Y=,iv:SEfXnegj/cY5HPhUv1V3MwtmzJIItUs7qa46cv6jswQ=,tag:Ew5Hn9QAbXilSbJaFQkzwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOG43Z1EyQ3JobkltYWpn
            N25LWUFpaVphcEEyQUc4V1VGSWZiaHU4VFdjCnc4eHNJYmFTb1JsM2ZyL1pGNS9U
            ejFVY3Z4OWJIVThZYlVEOXZTNUJqUUkKLS0tIC9LcE9KcTk0UVB6eUJqT2x0c3pL
            aU1SZ2pHT1RUKy9sOTZpYUptZGhPSUUKvizIVfWSK7eRx6k7pUybSPIWBtWNENvz
            oMnepwEKaRnOmCKxLGxWFp0aeVDNqapN1dXsy+aVi68HkD5Y7DSVBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-03T16:14:29Z"
    mac: ENC[AES256_GCM,data:Q4y6E6INb0Yac4l+/KHPPdOdh5+5sWVXdllBElBfcVuGGHNnHoDG3qpLgfi6L73XTxxDHqdIaZL+nyiHkgVlrc4eczv8aZw8zMJdwdBKlPj4IhBNJl3Xr2r8NeFoMprnQl4M3tiXNFORNGlLcNFy8bnlgnc/gtKpFOZY4pleEOg=,iv:0KJMHzccNNCYQCk4EQRR2LqCl9ltQKNuvx4YYHPpf/4=,tag:VNBW9QFU9VpkCJSlb+uEyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
