apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - namespace.yaml
  - limitrange.yaml
  - pvc.yaml
  - configmap.yaml
  - oidc-configmap.yaml
  - cluster.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - networkpolicy.yaml
  - config-backup.yaml
  - restore-test.yaml
