apiVersion: v1
kind: Secret
metadata:
    name: onecli-admin-api-key
    namespace: agora-onecli-test
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:TX2EXxFN7IhssfrpknzXb7yhKEJUj/rVFmB8uo6DtZXP81MVfnGD+s8zdqmKGI6CxBaw4BlkKOhpNBjuIEgc3R4SGw==,iv:jsob+yDp4GeC+cZ2UQEwRmG3745HiA+MnLkIBo8w4dM=,tag:sXjYIAOykPTBtxlEOhlFhA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUVlkVi9RWGtmcVdvR0Zz
            S0JkMk4vUlgyelBZWEJqejhadEVoQUd4Sm5FCnI4OHZhTnJXNEUwTkNBRzVhOWhU
            WndlYUNoMk9rU2JTQW5CaXBtNW44V3cKLS0tIGhSamcxc050bDBPNGdSd0ZzQUww
            YTlDU1Z5a2VhSkZtTld6dWNpSXNzODgKgW7jEjXRPbut3FVWKMMSm+Qvlcdn1rCT
            MZsw4aSAwSAV295uawSPg7Lnz8iDjibIBhoNZ+w/nu5+L/9WcDaY6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T17:12:44Z"
    mac: ENC[AES256_GCM,data:lo9n2otgozjeyRzx/TKG2fMequxVz/0r1YlcZRSlB0GTMnQDDifrAN/U1naKjsFDou711AU+vNu2itkkKH1nagHAT9rxbxJ2jq1W9jkR+EJMco2ezzKP1FKuW/Xu72b64DS2GU5G5oKVo765EN7N2yHuDHDstkQL2jZvJpeoj7c=,iv:IftmDvrdTfIrZnqVeVye1ufs3oJ4rF34noIC2xFPLxw=,tag:QdleycCyL8ZF1MWly9YOPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
