apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-api-key
    namespace: pocket-id
stringData:
    POCKET_ID_API_KEY: ENC[AES256_GCM,data:c+jO3Mh0qWGI2uudP7muo6g3xJBp6Im1jlVuzytHMsg=,iv:qEf4PvqrUzJqspxK3C2RSPjQye9hoX1flAm9gzSLG4E=,tag:nUoER/32wFzVROgj6xdYIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLODdZUkVnR0kvS1BCUmdt
            OG00N2YrcTZPL2dCdm5JVHNjeEpuUWNlR253CkVrTVlFRW91ejdVL2k0bVlzN0Ni
            NkRzVVlrMUFtY1JtcU5EY21SWGhDcTgKLS0tIEgvamZiMDRZeVhWaXNzMUtjb2ZJ
            U3dBZ09VemJnUU9aeUFJQXE0c1ptZXcK5jaFCX3qKX9YeflX/MM81U362fzHlc0h
            Dpl+h/6aw0AU7wFiP8tnqCmRH0iNQIfny7l7rTOYR0P54OVKr4+YjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T19:47:04Z"
    mac: ENC[AES256_GCM,data:bZh2DeimAVfroMYxRj2Xrw/HJZd/B2zq6VVd3uou1nwXsXCBi2+kFH/ds58N7/iy1HBEGdib1pf6gOVS3320uPU2sb31r07AvO3WCVKyCdm8xrVAEyDKUs17z2do0mk2rHiU72dccFLzKiIMTHpuRVK6EFpqq5LOKSTidQHLams=,iv:/botOvbvh+75Op7PODmA5TyQWpuWg9Gz3/kZ4WehOqc=,tag:gdD5TIWMB4pbltcw+wZ1Zg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
