apiVersion: v1
kind: Secret
metadata:
    name: agora-next-owner-pg
    namespace: agent
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Zicg5Dq4jE65mbiuNR5JPQ==,iv:nh8hEV4UyvlJd8qwb7uN/mlFK05v7lYliYrY5WdCa4o=,tag:nMV2m3EsuakTPG6zLmlqQg==,type:str]
    password: ENC[AES256_GCM,data:BKH8Q/IdoMQemo6TU/sIq4WavLTwiG64RyjDRP+UgSSPVC+MMgsX3CLcylE=,iv:bv7W2eXDhm9RE0HjMMCDPOcoMlaKKJf9J8mDUu+MXl0=,tag:l6BoGb+7peUPDSq46wN6mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhekxrRzJxT2Z3K21tQ1py
            cDVaZ3dkT1BWRjljUk0vZ2lmSzJZTktic1hJCmRKaTJhOFFxTldYR1VFQjg1L0Vh
            TTNPUFZzN1VXVC9oZ0Z0ajVEVGxuSkkKLS0tIEVIS0lUaS95djZmUE4wd3ZHL2xP
            WnhlR09RV2twS2VQd3pWRFE1cFVxWFUKQWb2xgCBRFqmaAvCAEjq3Hkin7uka5fH
            HGnoUb8ELsUZ2KBRx0I7RwLp4CQkfSqtqz18Ihqypp2VpIa/WzjFOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T20:12:03Z"
    mac: ENC[AES256_GCM,data:NMjFIZwnmK2J8br7E3rCeYpWcfqSTudjylyxiz1yZfh/tJ+KKowC26K0lJ6BnBmyrq1Fe39hR5Z/54PugxHpqiifuS+YiVsX7V7/dXccrEYxrrj0/fDAZSU7IE7YuKIu3oxDPK6IUY2zsS7lC2c4PPvL9L9ecn0KEr9Z/sDBFRY=,iv:KZB/Jld9kUdinpix6UVx1HB4x3g9XBD6ChiM2XU9GMY=,tag:NCxoxC4a8GGlDFEEeeBHSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
