apiVersion: v1
kind: Secret
metadata:
    name: agora-web-login-pg
    namespace: agent
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:rK4l/F1ip7wiCDfzvFtk,iv:mtHZ+FeWGQfxc5T2paXA8THpVfEllZuDIiMdtt/2CVQ=,tag:hxj8sAH6RK7iPtGsJx20tw==,type:str]
    password: ENC[AES256_GCM,data:BEDuI/ygl5Ax0fX2mjk3PF35ey2ABqJgZ3LTvyd7x5p7xiRs8OnWNhYv2u8=,iv:eh+z6i5C0sHHfQ7vKexK8A8j0U49pEaUs11MFJ7Uh80=,tag:6w8HGYa+b2e0ek2UWEdB6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSU4zc3ZibVcxSTFkNUg0
            RFRGbEdlVmpub3dtdW56QkZ4ZmZTc3J6S25VClN3WEFEK2xBSkxZN1ZPcjlDNjJZ
            UFFnRG1Xd0lHTG5DUy92UVI5SUMyUzgKLS0tIDJ2Mmh5V3pqVW5hZVZKUENsb2p1
            MzZEcnRDTFRYSkVCSWpuTmxaS3J1WjgKbFqYi1+b0OWsxQhhX1j2nXmCJK7xrzXp
            BQFGJUCo6ZUHGBsiz19OVmWJHpLzgIos14PnNesxi1ckRDLtDqCsZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T20:12:03Z"
    mac: ENC[AES256_GCM,data:3hT7zo2mOEBP/tWkoWr2ZN+nzGfVpP+GcEd0sH5ZX8QP5zQ+2r+0On6M5aU6avRZE94dZINE/3aV2fMz05ddUvkSxmtQMCnqau3FN9jgG8FWwlMCtCt9ewfKr4hCxv2+069V22h7vr0Ac9EGRQnzqOuC0EcUqwRv5dSe1g2PV2E=,iv:mxZs+nVij6s2rlhcglVlORENTJWlUla32FaqCWmMTJQ=,tag:OdhV/yqBiSgyUyK/FZjsXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
