apiVersion: v1
kind: Secret
metadata:
    name: agora-broker-login-pg
    namespace: agent
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qTPmqNWofAWX08t/bLwCOP7l,iv:xWBU6jvPzFZc+5N2ge1Pd7e6CJfCgJEdUiM3PoEO5rQ=,tag:kt+i2DaPoiL5AL1pi7YfKQ==,type:str]
    password: ENC[AES256_GCM,data:fvTrdTjy6JwR/uZ+0yVjkg3hL79TXs1h+nCp9Ef9xIfRIaCtSki4jp73xwA=,iv:zCPcqCp+92zjW3Skeph0Asn98n6K5csZteh96fM6tJo=,tag:FOt4H2r8L1BNTVhwM+4XpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMDV3YnNGelV0MG55T09K
            Z0pXYUp0QXpsSVY3ajNvM3Z1T2hzMGpqOERrCnIvb3BXVzZuMTVaTGdDU0hDeExn
            SDgyZklGMWlNUzh2SkNkdm1PeFgvL2MKLS0tIE1aUzhWLzhrRkNhMVVnOUU2M3Mx
            SEpVdE8vM0ZrL2hqaG5FK0FaSGU4RUEKCpwafAuPalqGReSFsF5vE9Tw2hsl5Hnt
            zuWDyxGkHudgrdrLetiKrnhR/TT4UULxCJcWWtwCsMQsJs7y5R8vqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T20:12:03Z"
    mac: ENC[AES256_GCM,data:N5AgAp075YU4dSHC63CNtBUEr7GKp9hov/zPPBL8h72UKpoVdekS/wY9RnleCDae6z5ZO5HO2hkoqpRGc+alo87plisYd7xgYVV2W3w0GxApTOB6OYssDyubXt6kEZlgwZDS/fHUdrq55NSPZDR320Uqu33hu9Zd4BbcTgABapE=,iv:sq5UOKUfnn74zt5M0dohH1Gh/onGi0dlremim6b1fgk=,tag:OMIjDPEJ3woE1AAG2RbQCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
