apiVersion: v1
kind: Secret
metadata:
    name: agora-controller-login-pg
    namespace: agent
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:H8AHYd0PsM9iVN0vA9WYDYT3PP+qnw==,iv:VEJLgRMSORfaq/WIB1vSISninQcZdWA6Lt+bB81IpGE=,tag:X8QyuD4Ijuy/sEzMD5pjPg==,type:str]
    password: ENC[AES256_GCM,data:fAby1EwBO9vKD18ZT1wUO4SK9BC0Flj2by2tyR7N0Wfp1lFWY5GTinpFNTI=,iv:doDzAuDgnJYtYlm3/iZ4t5uTOB+Zv+uYMius2g7KOLA=,tag:GodHRxsbH5qmvxhy84Q69g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cjkxRU9QeWJOTTBVK0NK
            dXJvdlhHZ2pMSnpwaUliZENnUmpjZ1pUd1NBCkxRUnZwcWw4U1dWdEtWUG82T2Qy
            a1RPNDJkSm1VZ01DSWR6d2wyTEkzR0UKLS0tIHBTUFR4UUJoUnR2NS9FUGdrWTVY
            azhtQmhsZWg0STdqQTFReHkzbElUVTgKlUv49tBp74R5XLdxqyouSCQhGat1QOo2
            dp/4+zx8leKgJNS9wZ2UTBIiIsg4x6euRrSXdhEijXTGYX97t8GLYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-05T20:12:03Z"
    mac: ENC[AES256_GCM,data:8nynZtnivDxTvSZWwEOmMh6E7pmx3oTVJgB8RXH3dYyrQhaWTcO5C0aoP0PZ4+EaCKufRwbirFvhOihOHzrZ9tYfb2iZOM2j0pnVF5OC0IRlTEjHn95EeznjV0GvdmDx3mNeAkmWV1cM8U/Yf4KBgmY8IafAzuC+piTwIz1dNeU=,iv:emBv/w9s/uWgnlXaUQuD2VqltzycCadwr2faaB/l7yg=,tag:1AqZUNSXKcVGzyLH/fnrtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
