apiVersion: v1
kind: Secret
metadata:
    name: claude-oauth-token
    namespace: agent
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:nvjDcLkpX/JlXmWDwoIu6VR4n5rpB9e0FD6UJPDWT7SclRO8vbzur5xh+UCfhhDqfextTvXLuVbDV3nRZuEPf67XuH9hdlm4BshlFtqJhrwdKniGV5gS5B9AqH/ZZ5jTfLp6oGw48CVSSFGd,iv:HFBD65yDRE7cdc/MoxeR/uoJtxbTRm67lGnHMZWpr1k=,tag:gxIhtzVWfOs7grWFVIpnfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdXp1Y20zcDZTaGY2TFg3
            M2FPSUNrZm9wOFV3QzRuVGVWa0s0bEJKY0c0Cm55SEg5L1RLNlA0c3YvL3Fuc0h3
            WkNITHpSRGlwVmx0TXdHK2huU2dJK2cKLS0tIHphc3VHaTI0RHdVU083cGtYQmEv
            RHFObG9EMnNDU01zSCs1OVBKRERkc2sK69LnUGrQdXtDEjppK0aCuzA9pVc26qcg
            mCj5gqjU5JDCJfeA10Do1C7DJmL3ISqx2EeFEggxToiZByA4Y5fDjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T17:37:36Z"
    mac: ENC[AES256_GCM,data:z69Q7pfhmI9Gz1AxGDoFbCGKCkE9LitE+zN8D4srDc6sgXM8L3M+kfK5sjX6DBL4v6CUUxyHGOa082pnXcdoiJAoCID9faKUaGBPslZCbXbXadm4CxZw14IftjvzyweYM9sShWVD0GD74B8pJ5TTth9NMXwhdBkQD8FLlEmWcuI=,iv:Q9DSE//IpfkgzLG+shRTAfJTBCL88ygDToLwfwNtYII=,tag:yYiyzSFI95QtbDjSo8tK2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
