# oauth2-proxy OIDC client + cookie secret (Pocket-ID). SOPS-encrypted.
apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy
    namespace: agent
type: Opaque
stringData:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:DL8yDHeoWcE1NegmOOMDAmnrqswFHsVEU5XqM1rMZvZkxcaB,iv:wS6dNUd2/ul3T6/dpeuArp4iwXbdOFYJkEVsovn4id0=,tag:kh4P85uwn1zZyod4sR6XaA==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:BFuIX0O+CHsschNBeVE8g6yyJCLTu6v5MMtTbQSmjEU=,iv:KySqxY1kQcT46AXsOUPKQ6C360VgCjOFMkAPCxEPM6M=,tag:1KYGaJ9NJu1E95DbIl/UfQ==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:cFo2rO5lIVD23gn8z3mqKeXyf2QTGzXSGlKGJioL7Duv9tvKzX7lYwtcAK4=,iv:2pX9ZysPa1KjQHII18cC4hmbGcut5ugPeHKp4KrtJ1c=,tag:+pRF9Q4vVyse+ZPHTgkaOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTFh6K3ZIZmFzZTRqK1hZ
            cHFjeXl2QXNWbVczRW1DSkpZVUJhQTlkTTE0CnBZbE9ZOHpTVHFJekFtVDI5OXhD
            cjNIdUZvbnlqYU5zUENBWVIwTUg4UDAKLS0tIHpoN0x2ajRkWnVLaXBOdnpEdmVl
            bTYwOUFmNmNkbWJhRGdUa1FRVllYbFEKcfMlT2dlHGouCciMqMPLnBm0LTJILu6Y
            /1aGkdnqwwGytMurr7EWjHg/GjJEXuaxm+4f4arXf3bhe6kQsVfwjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-02T09:06:12Z"
    mac: ENC[AES256_GCM,data:sPHTL6jhb3MiTa7zae+O80J/tb59CQpKMQXy21lBMcYnB8LxoVI4RKO9VckI4zvtA+I4jY6RDgEjtnVpAXN9jzskbE9sfpgDNiyC5ZkkoG5xbO6fiCzAQftn5wncq9pVJPamn8zaBidF8PeHqJx1EZWZGGCX8EApGKt+00MyCu8=,iv:e2KnSe7KPioQgWbR/yaqOkowwhBDhZ3kDh2cePTm0QE=,tag:Bn68wzjJNpu3YV5e4wivmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
