apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-broker-client
    namespace: agent
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:igBOebDM0G0JBvk0OJ4UVPvW2JfjT6lP8PCTWimAuQw=,iv:M9IEYfzdP1IngAQDwYiEcLRwwuFJWJOHQEUbv9GNxf4=,tag:FG+c7WGOdLRRRaAuqzNUMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJd0dTZ1h1MHFFc0NhdUVp
            bXVPMEZCNzJJMlV2dmhCeW5xcVlYeTdoVkdJCk9GWEt0d3ZCMVJCdXQwcGZVOWNz
            VTFNUmdBWThiNVFUVm1ta2NORmFOMEEKLS0tIHRsQ3d3Tzk0OCtLRVFINGpTZzBF
            T3lVY3dZRGV0QnJrTmZkbE15L1JrZXcK6xqhDFsWybbamuevqpHJeRafvGJqgEQv
            ATEojqIDQ1gXti/0J37hT9aNIbOb+lQBPijwhpR+NfboyuaEmUr1mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T09:47:07Z"
    mac: ENC[AES256_GCM,data:nnb3yJY9oOFmvQNK/btvLZ+hpLl/86YYmRBldFl1OkCh3WqIQhVsbh864F0MHqAdGpISRCzcCztYb65OuXWSCNWE4tQe8Hbor4RBTg8PguiNupqE74qRFhrgFWq2aG5NTLf7QZ6p2Umx+4wshuzeLQP0izRSOv4qfXrYW5muk1M=,iv:+yUkpaOg44G9YkfKQ7zPC2U75mwO8t21k0SgOWmNxMQ=,tag:8eoIzI0IPkH/e0B99ItXzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
