# The service actor allowed to publish a catalogue revision (POST /v1/admin/revisions).
apiVersion: v1
kind: Secret
metadata:
    name: agora-operator
    namespace: agora-system
type: Opaque
data:
    PUBLICATION_SERVICE_ACTOR: ENC[AES256_GCM,data:T0diJmPzD5KXEHr66aKYrdabX42kZhVVK4C1Sg==,iv:UAgjCVrpkGqBYmzpGywwfl3AXZoNRWxeg8Dzh92Xm/o=,tag:+FzSBEmujRC6DJDtURdvRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySDhXZkQ2ZjF3ODRRT1BN
            bS9LU2xhRzFQellnTkNkcHZmRDYxYVVtWVZBCnhJV3BhOVBGY0FKOFZUWUg2WS9V
            cU4yaWRPaEF4aGZKZXpEMjFUdG1taWsKLS0tIEppOVRLS1FRUHcwaU1ZUEZzTUov
            TnQvQlZseUlpK0NWdHFZd21FZC9Xc3MKnPQAIQzk742ZRNriYuEAmQRhkcMpD5/s
            mM8LahxT29/eEC/j27aiTgXwXiC1DmZhASDPi+THKbFhxfLiJS7H7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T06:36:22Z"
    mac: ENC[AES256_GCM,data:B12nui9+PkKkma4JKy9ORWion3ptHLK/DYK4UCYPoXxJ5htrGy1FMioI+/HKvD6mkSyDQLeZF2lJSLE2Bo+O1QH+B2bg+kp/9RwDZVvABCZHCkNqOMcgO+vUn3N9PT5+LmC11EswQ1HkUcNOG5SnMG2opiYJVdwk+Ua907U/gjI=,iv:j/nIZF1QRnu64EYGowSHD3dTxUkDGnNLA7tEx8Afdsc=,tag:pWJ9h6sfi655zljIq8yk1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
