# Read-only GHCR pull credentials for the private engine images.
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull
    namespace: agora-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:fXwoy8dGe1ORyHPa4NS1+sRKRDWGFrkhjM0y3TGzP62kBrz/lEVcC+bUBZMiTOS3Db1pdURCU+RHK8vryuSdWrOgHvwdbgB6eyhyiroGiKdhx8H67UmIwYZKyz0K3bVEFSzlMiijKgaIlb+biCdry/hs9kIukmoYmJwfUs3cIj8E5zu0wgnwbYB+ypeSurCWPgLAFGzNfoVhqYOFTd+BSqoWJwiYpniLB09HkkhcS1yv89BMbI8/TJtYN+O8Lfio/hNp5HFwVHU1FfAcujhRHS8IjNXHgxEFLysWZ9/PN/2h3+YAoG3OZItIo3PxJBEj1fz8Gs6utD4lXQ+AA1ZcoQ==,iv:9CmFZX5djdSRk9nLl1tTE4qOImnJf5yGbONc7L11cPE=,tag:3BkipQijgugu/4ThtYzAHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dEo4cUo1U0l6SlU3THoz
            SXNGMnljell5OGRsYlVHUVlkamgzUGFQdGh3CmNNQ09XcFljWFhKVXU2aUcrRXVK
            cVpsVVBHWlVvZ1pFY0w5RHBVZkx3ancKLS0tIGJiN0wwSmJiTUY4c203NzdXY3dx
            OXRmL0xXNVo1YXBJTTFGSm5IcnJreHcKOpZlMjHwtyMADfk0yMRLbO/Uk//aKUt3
            Tqmh7JI/jJqZ1ixvS6IT3u0RELOrBR9frZjR8JUfaPlX2IfRf+uBKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T06:36:23Z"
    mac: ENC[AES256_GCM,data:wb3kIeJsV10NdozcRdZ12oWaIRs2JmT94+mGcVgCwh1Et0+u+PYMlhR8Jemaz7qc4TqQbcdG1gMBLzQU2NtHGtDl4t7BaDrW0IgC4zH9nglMoFP9hUQWAH2tdMWfpAOdWvcA2iVO/H5qoYaKffnBJ2sxG0yXOEEcyl9EuPw8Nn8=,iv:CMShtFeza545BrTEoa3kqOAxMBi7uw4ASF8SV7sKFLg=,tag:PgKaW2GDgX0N+B/aE8BgdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
