apiVersion: v1
kind: Secret
metadata:
    name: gateway-ca
    namespace: agora-gateway
type: Opaque
stringData:
    ca-cert.pem: ENC[AES256_GCM,data:rmNzX24hxHlEgeA2t6vBK3ns8hkFGtRaXsJhaG5doxnQ8vClOtDzT9j6vOs7vzYjavVmPELFI9cnBnao0euFRJeDQD4rO1Ize6Ifj6jOokKkDH7ApNTfOYeG6HSdqIRJdMeK2kLHn8Zl73ibGAy9LPP6bluMkpXaAiiNeaJNy4Yr0P7MVS+LZ++DpzZL0hvjoneZDBg0IIllTJcb63E+9MsvfFtumNyJB/Mvjm3J1AEWq8bgumSKBc6Ukqipb0AehVxfH3D6JTElF7MHvVDLhIFNtrGLz7zIGDAZ4cnwqXxZyuM76MiWcXWgbiyiqA/bxZYYsZq1H28cgB6ClD0OtmmC1LqG5AcwFlYwqScI8onTuaCfvnNkKofZm0CoKjtGEK5HyQzIfAQS/OjeIsl5IoBqv9cuj2FCWFtydSRNe8OPxcOmB50YCAz/HeMazqpIDO8W36YUldVSFuqYCShFR9tKY51f1xY2KpJJBb8jGOP5YK0gElEfdAN1QsINCxUovIdAyAeUBk7Bmi/oiDoPl6T/JpWkg7dsyBHfXlFgZdpeHOm14+BINIaYufvNNYYEGYWhL4sgo6y8AIgc8/pTOV6xM/fHf8qzghzEH2My+AbfNRqvDpAhNgEUGaRC6je/AYyGS1J+5wFVXPnstnWFwwTXbhTvF40089VfDjzIikKoBsBS6rux/OXVAuCh01QliL4H8UhG+yMlp+ZdnUEwJA7mJ3KMBQgynbgI0kIz8lb9RygE1y/pAZlZ2ZeClBy15Oc6JFAqGUdpVXzax8wzayvwYcI3I8NoHd6OgfJ6WtYpgcLOoO47LTQ1Lg==,iv:nTS9+D4H6YY5Kd4B4Zz+NpedOtz38Ob2Uo2u7bGfhN0=,tag:fMt42bZL19v7p9a4+8SKBQ==,type:str]
    ca-key.pem: ENC[AES256_GCM,data:zmZHAMxEGC8LMMMbljo476Y4XMMSgp8nc90TgziYVvU1acxvXFTS+GP7BDRSBraotPRlZIuBPRFxnfii195HlaGczPn+VHRdPNLwjs1leiE7gOCSb2JmHT9Mx4Ak0hLsboSpXKC2q3UMxEidUR+GjT8UREveFdoJnZ7ZqiA3f3AZXIWqJE5QJXMjNdb0+G3F2RygtkQ4AbCHPWlyfx0NknSMJKBhzW0y0W9z/M74Yb0hFxgWIqstNOTZ+EwQg0OZfuTb7pYoXBuw+rN0qhk334Ipf9G4UKJdBrmW7xNtffih/c0=,iv:NynCA4FUtLwROMVuOEbc7LdKfOyq/Yd1kpw6RRJAY5M=,tag:i4emeBncxrzLynssy+D7JA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRHRXc2QrRCthbkFWd2I0
            cVZneVFQWVZ4Z0wwSHh0KzllTXpQQnhiUTJZCjRYYndST2psc3FCMjBEazNRU2E1
            dFNoL1R3UHV6QjlUS1BPVytkQ2pIRnMKLS0tIFV6YXN5QUhucC9MREx0M1UwQW9W
            YXkwL1h3aUhQYlYxSUxZM09IYnlCeTQK4jKGvU/9zQ+5vYA4OZEx/3SKnQyc2Nr+
            WW6tcOJtJMHCRmlMitFxq2gKIwFsEA/gKlfe1zm1W5LbIk21KGEQgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T07:12:14Z"
    mac: ENC[AES256_GCM,data:8+TYa16MNT5kG5hqOl2q8wudqAItRoetl48c6HAxXGHft1Mir1ueMVQADpK8ReGi5LV6Y7MffykYiBRAAU8XPQG/+jNASZIUg8Mx+8RjvOxR51r1TVFo+p/s7mqlWL4CgD5qEK1rgREeeKrGvMzzpcMjbEAWP5MYAvhN67oDKgA=,iv:ruHEc+jKkEtA7g2ItrvpkzEjYhp4fQMpu8tZkgrGT8A=,tag:73cyqga9eeDJluGP8x/SrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
