apiVersion: v1
kind: Secret
metadata:
    name: upstream-credentials
    namespace: agora-gateway
type: Opaque
stringData:
    anthropic: ENC[AES256_GCM,data:6+OWxB47I/pRIgilT9PslcR4W/7NfuA1TFPbRrGsj11XepYD6PQmD85O8w3hlngf3FKleMqMBCe+v3jvItcM0myMOIXNTR9KhdKxqTWcBccs9KSw87xib265scgoICr71wvFnURbsavQciP9,iv:NwDO9Agrze4RLsrgebqN175YGwmzbjDzZW//sshdCdQ=,tag:+XqqnSLNNDj9obuac1+A0Q==,type:str]
    github: ENC[AES256_GCM,data:tJSN+ISCbS3WxxPLGMeSzKYEj9sSNMbsdCwtrfUBVxyYB5V8PeebOS5ahO46e7tbXIC8tta0lw72D0CiIfxaewzzsBGUlhFjLINj87gtU7RZ6VaKVx9iLFs+sAwL,iv:IkVCeGog5+9fLs4kZn7lMQcXuYGy+WgutMUIayB7S/k=,tag:xaS18yuYL+xfCN8hfb3Ktg==,type:str]
    github-basic: ENC[AES256_GCM,data:BJ726PstfFQOfOJRglIGNdnUmy7UklO5LBv2EJPl9SyMiaZCeMLL9h+94XfRphVBf/nKKDKRlj028ldIkJ5x5Ym380sEL4RLwSo91GIcv96n4P6neSQtpjQg5vDckvMuJaI85NR4Jqc+wtbhcQu2omjpt/psEFyr11ZXv34Wcj3VsD4xatyZ9lvWSr1mehUs,iv:sUQMkT2Kvne1Uf9cvufUH7VF6y8JvHb/JZIADF3XTpM=,tag:HQj+iFUchR/6ZbL9v014cA==,type:str]
    zai: ENC[AES256_GCM,data:fiZ9hXweTHe/G6kTTVffDK6LfnCmcJG6bBhEMC8myu66clE0AgiukUgAJ7zGwtMpVA==,iv:EFUjdyPZ8dDfpI4GEp3F60xoPAU72fu+jWUkEfc6/d8=,tag:5xka6KI7PDXhsDTRedeBZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeHBkUFFNWnk2SGJnNm1t
            YjdIemdaTHphSElJVUx4clh3ZVhXbHdGY0c0CjMvd3Rscm1GdC9EZmVYOVVGaVlE
            K2dpYTNWZE1QZjJDWGxkVk9CVWpVTTAKLS0tIGM2Yk5wUHdLLzJ4MDRVNi9nR2hI
            RnorWHdrQ2xGMlBDMkc0VkxVM2txaG8KHlcxEYaDeS7bO05jSguVX3HUIUODANDv
            /8Ukk71Fj2JhU9/V5lnrUizzAU7HaaX53wiHoPsJh9Et01/CsE+/Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-04T09:01:12Z"
    mac: ENC[AES256_GCM,data:PJDXsbJ79bJNNdYCoZN81T+4WO+3qTzuTV2wopOefz0+l2FXm8gN4ZrFUDG8VCS6ilerlU5Ztl3kqy7nTndGmRxIvES0MTG2QwM7KKMuyGc5Q6kQn1kzAJh6sVw4PnrHw1iQC5mlCy9hxdisfQ5tKt/EN4W5Fcw/wrVWgIQMAIg=,iv:GwbuCOEWNTZi/RKUHwqKUpnuu6LaE3/9wXVcLpQoKR0=,tag:0yK1D73pNoJpe6LjUUJX1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
