apiVersion: v1
kind: Secret
metadata:
    name: upstream-credentials
    namespace: agora-gateway
type: Opaque
stringData:
    anthropic: ENC[AES256_GCM,data:LXHUCzYSjvinpL1V6xIpumRRTYml9HnTZVyyUSPYxY3WwR6ea0Y6guNOATWO5M0eqeYoVTIE59CDZysNWoohANEpzxSRhh9XD4XoFpNiD9zU+jqNJAjtUez/R2Q4jWfLP8X6WMybC1KLA3Bm,iv:9awgUzimeM9kNB8e96G5V/oJBdcDHQ4+JmkqJleqiQc=,tag:lGJWB0q4wNyPw7Bd2jU9DQ==,type:str]
    github: ENC[AES256_GCM,data:mw8B8zuDW9xKzqgllMpzSUMyFAn2TOVtk1ZTQewTbINI,iv:+8an3IR86uKdJRGQ8L0/7PT5Nuyoh5ZOvW2Takf4MNQ=,tag:Huy7sGnBaOl7tCRy5HQEHQ==,type:str]
    github-basic: ENC[AES256_GCM,data:TXMYK73Z3zZmg/RQoUTX+niiOajp0QmQRypB4qQolYLnJBVUc9W2PkX9X+HC+WgeJZs6iTUP+k5payf178TMhw==,iv:kXvBiNupEzGT/CwDuiJGKAaA7seqd6PCsM0l2DSwpis=,tag:QwM5QtnTM5CA7XIxUwUAug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPb01SQVErTyt2STlRM3Q5
            OFRWV1laUExyUVZpMkhBcnNkYzMrNUpNVENZCkVKbmdzQnU2T01TTnUwNDhaRTI1
            R2VDYmMwZFlzZ1ZMcVduaDdpSFJuTTQKLS0tIGdsUkZrdUNac0dzT01qM2xDbE42
            M09zRUJlSk5PN042QnVKMWZ1SEJFZk0KJSL7vOXldwOWIO/TNen8INKPDD35AbMS
            iref01QYL33R8yd16IMOtbJiNUuBdNFxyA3HvCW9B/CGSq707eWBoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-29T07:11:51Z"
    mac: ENC[AES256_GCM,data:Q+UPkoMRqlniYm04xTUTg9InrG+5Qa/YS7PYqRVBST62g67q0FIxHvGtg9ZIjqEFNncCycAzs2qMuhCyGCT9M3oH7iQTWG7E9OrVD6evdGwHE1r1Rp2eV8otNizmb1SUDhIA2zimmf90dPgyKAV6s3powBBNr0FXaKZTW9Sdgic=,iv:gjRMULVaPf75wMsxtorw79kLjsqVY0m7nE441w4qZYA=,tag:qvFa2xSWIVIqUzsQCNoqVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
