apiVersion: v1
kind: Secret
metadata:
    name: upstream-credentials
    namespace: agora-gateway
type: Opaque
stringData:
    anthropic: ENC[AES256_GCM,data:6+OWxB47I/pRIgilT9PslcR4W/7NfuA1TFPbRrGsj11XepYD6PQmD85O8w3hlngf3FKleMqMBCe+v3jvItcM0myMOIXNTR9KhdKxqTWcBccs9KSw87xib265scgoICr71wvFnURbsavQciP9,iv:NwDO9Agrze4RLsrgebqN175YGwmzbjDzZW//sshdCdQ=,tag:+XqqnSLNNDj9obuac1+A0Q==,type:str]
    github: ENC[AES256_GCM,data:7mmv3AxC0Sxgxk0Ib84XnJiGo5KzbG7B5I4qwVNCOQQch7gRSE74U8cKDYPd3ZYnmwVrsbAvnzZAxpBJt0CizpBa96BerKH3Cztte94wudJRMagqxy0MlVoQ+jqO,iv:ufhPADwHl3q7sBd1nR3raUGRqVJV4kV/U39pArXT2cg=,tag:7fQuAJ3RqOa/5Tcjn/GU5w==,type:str]
    github-basic: ENC[AES256_GCM,data:BkaEGclGqdq4dGX+t2ajNZZXQyFGwN99/FBOMDdbmbWsquoT9US3qiqGw30XI0QCxysTB5YU9SZrrQO0pMbkuQj8qTkYX8JXrdS6ZifoFdF3hBnJlT0plTOyhPFIYTYJsSDXrn+RbN/N6SjUmCGDuK2THEEv9giaQPcOAHzkvWwKRm9iLW9SxGYnsJiCUKKE,iv:y5pE6IJA9DWBL4iZkQY9xPOEa3PDLrkE6CEl71piAg0=,tag:B3CDuUkIUq7rWNEB1n+GeA==,type:str]
    zai: ENC[AES256_GCM,data:fiZ9hXweTHe/G6kTTVffDK6LfnCmcJG6bBhEMC8myu66clE0AgiukUgAJ7zGwtMpVA==,iv:EFUjdyPZ8dDfpI4GEp3F60xoPAU72fu+jWUkEfc6/d8=,tag:5xka6KI7PDXhsDTRedeBZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1evm208aw8uk3m7tcn44m724hu2738hmwdqefr3897zlsvnqwdyzsxj2hp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmeHBkUFFNWnk2SGJnNm1t
            YjdIemdaTHphSElJVUx4clh3ZVhXbHdGY0c0CjMvd3Rscm1GdC9EZmVYOVVGaVlE
            K2dpYTNWZE1QZjJDWGxkVk9CVWpVTTAKLS0tIGM2Yk5wUHdLLzJ4MDRVNi9nR2hI
            RnorWHdrQ2xGMlBDMkc0VkxVM2txaG8KHlcxEYaDeS7bO05jSguVX3HUIUODANDv
            /8Ukk71Fj2JhU9/V5lnrUizzAU7HaaX53wiHoPsJh9Et01/CsE+/Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T19:27:07Z"
    mac: ENC[AES256_GCM,data:694rcjcPrLmMBEjhzfb9qsmKPU7VUWifouZFXJmxQpthIOXJgC/CUvgnXBNdfzhMo5PbR5Jvq8vBaWaf7ufxchxpxCYLif7uPsNqhaw7wC+rgdzhXn6KGlfVslAk/4OrxLV+xTVvSkLtaX9Rcud413+BrikHbpaK56EvZND6bfc=,iv:2XTaPbzCyp7lHdai+QoggHLokxuSKycaINjsSHZoObo=,tag:RpenG/DxslQvaTOhRifGyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
