apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/kubernetes-sigs/agent-sandbox/releases/download/v1.0.3/sandbox-with-extensions.yaml
- networkpolicy.yaml
patches:
- path: controller-patch.yaml
- path: namespace-patch.yaml
- target:
    kind: CustomResourceDefinition
  patch: |
    - op: add
      path: /metadata/annotations/kustomize.toolkit.fluxcd.io~1prune
      value: disabled
