apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infrastructure-sources.yaml
  - infrastructure-shared-secrets.yaml
  - infrastructure-crds.yaml
  - infrastructure-controllers.yaml
  - infrastructure-configs.yaml
  - infrastructure-gateway.yaml
  - observability.yaml
  - apps.yaml
